import Navbar from "../components/navbar"

export default function Output({fake_percent , type}){
    return <main className="bg-black min-h-screen w-screen ">
            <Navbar />
            <section className="px-[20vw] py-[8vh] flex flex-col items-center  justify-center h-[88vh]">
                <div className=" h-full w-full flex flex-col items-center justify-center">
                    <img src="./panda.svg" className="h-3/5 my-5" />
                    <h1 className="text-white font-bold text-4xl mb-5">The image is {fake_percent} likely to be generated by AI</h1>
                    <button className="text-white bg-main-purple px-5 py-3 rounded-full">Upload another file</button>
                </div>
                </section>
        </main>
}